version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "America/New_York"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
      include: scope
    open-pull-requests-limit: 5
